import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import Footer from "@/components/Footer";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "TenaDoc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className}  antialiased  `}>
        <NavBar />
        <div className="px-4 md:px-8 lg:px-12">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
